# Generated by Django 4.1.4 on 2022-12-21 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asset_Transport_App', '0003_riders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
